version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/bitewise-frontend
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 30
      runas: ubuntu
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
  ValidateService:
    - location: scripts/validate.sh
      timeout: 30
      runas: ubuntu
